<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try {
            ace.settings.check('breadcrumbs', 'fixed')
        } catch (e) {
        }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/post">Post</a>
        </li>

        <? if (empty($item->id)): ?>
            <li class="active">Make New Topic</li>
        <? else: ?>
            <li class="active">Edit Topic</li>
        <?endif ?>
    </ul>
    <!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                       autocomplete="off"/>
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div>
    <!-- #nav-search -->
</div>
<? $textForm = $form->getForm('text') ?>
<form id="" action="" method="POST" enctype="multipart/form-data" novalidate="novalidate">
<div class="page-content">
<div class="page-header">
    <? if (empty($item->id)): ?>
        <h1>Make New Topic</h1>
    <? else: ?>
        <h1>Edit Topic</h1>
    <?endif ?>
</div>
<!-- /.page-header -->

<div class="row">
<div class="col-xs-9">
    <!-- PAGE CONTENT BEGINS -->

    <div class="form-group">
        <label class="block clearfix">
            <?=
            $form->render(
                'title',
                array(
                    'class' => 'form-control input-lg  slug-generator',
                    'data-slug-target' => '#slug',
                    'placeholder' => 'Subject',
                    'required' => 'required',
                )
            )?>
        </label>
    </div>
    <div class="form-group">
        <div class="input-group">
                        <span class="input-group-addon input-sm">
                            <i class="icon-link"></i>  http://www.goldtoutiao.com/topic/
                        </span>
            <?=
            $form->render(
                'slug',
                array(
                    'class' => 'form-control input-sm',
                    'placeholder' => 'Url, No fill will generate a random url',
                    'data-parsley-trigger' => "blur change",
                    'data-parsley-remote' => "/admin/topic/checkslug",
                    'data-parsley-remote-options' => empty($item->id) ? '{ method: "GET", dataType: "json"}' : '{ "method": "GET", "dataType": "json", "data": { "topicId" : "' . $item->id . '"} }',
                    'data-parsley-remote-message' => "This url has been taken",
                )
            )?>
        </div>
    </div>
    <div class="form-group">
        <div class="widget-box transparent">
            <div class="widget-header">
                <h4 class="lighter">Content</h4>

                <div class="widget-toolbar no-border ">
                    <div class="btn-group">
                        <button class="btn btn-sm btn-info editor-open-media-handle">
                            <i class="icon-plus align-top bigger-125"></i>
                            Select Media
                        </button>

                                    <span class="btn btn-sm btn-purple fileinput-button">
                                        <i class="icon-cloud-upload align-top bigger-125"></i>
                                        Upload Media
                                        <input type="file" multiple class="editor-upload-handle"
                                               data-connect-editor=".editor-content"/>
                                    </span>

                        <ul id="switch-code" class="nav nav-tabs hide">
                            <li class="">
                                <a href="#format-markdown" data-toggle="tab">Markdown</a>
                            </li>
                            <li>
                                <a href="#format-html" data-toggle="tab">Html</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--widget box header-->
        </div>
        <!--widget box end-->

        <label class="block clearfix">

            <div class="markdown-editor">
                <?=
                $textForm->render(
                    'content',
                    array(
                        'class' => 'form-control editor editor-content',
                        //'class' => 'form-control wysiwyg',
                        'rows' => 12,
                        'required' => 'required',
                    )
                )?>
                <?=
                $form->render(
                    'codeType',
                    array()
                )?>
            </div>
            <!--
            <button id="test">test</button>
            -->
        </label>
    </div>

    <div class="form-group">
        <label class="block clearfix">
            <h5 class="lighter">Summary</h5>

            <div class="markdown-editor">
                <?=
                $form->render(
                    'summary',
                    array(
                        'class' => 'form-control editor editor-summary',
                        'rows' => 3,
                    )
                )?>
            </div>
        </label>
    </div>

</div>
<!-- /.col -->
<div class="col-xs-3">

    <div class="widget-box">
        <div class="widget-header widget-header-small">
            <h5 class="lighter">Publish</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
        </div>
        <div class="widget-body">
            <div class="widget-main">

                <?$status = array(
                    'draft' => 'label-info',
                    'pending' => 'label-warning',
                    'deleted' => 'label',
                    'published' => 'label-success',
                )?>
                <? if (!empty($item->id)): ?>
                    <ul class="list-unstyled">
                        <li>Created At : <?= $this->tag->datetime($item->createdAt) ?></li>
                        <li>Status : <span
                                class="label label-sm <?= $status[$item->status] ?>"><?= $item->status ?></span></li>
                        <li>Autor : <?= $item->user ? $item->user->username : '' ?></li>

                    </ul>
                <? endif ?>
                <fieldset>
                    <label for="status">
                        Status
                    </label>
                    <?=
                    $form->render(
                        'status',
                        array(
                            'class' => 'form-control',
                        )
                    )?>
                </fieldset>
            </div>
            <div class="clearfix form-actions no-margin">
                <input name="__redirect" type="hidden" value=""/>
                <button type="submit" class="btn form-submiter" data-change-name="status" data-change-value="draft">
                    <i class="icon-save"></i>
                    Save Draft
                </button>
                <button type="submit" class="btn btn-info form-submiter" data-change-name="status"
                        data-change-value="published">
                    <i class="icon-ok"></i>
                    Publish
                </button>
            </div>
        </div>
    </div>
    <!--widgex box-->

    <div class="hr hr-double dotted"></div>
    <div class="widget-box">
        <div class="widget-header widget-header-small">
            <h5 class="lighter">Image</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
        </div>

        <div class="widget-body">
            <div class="widget-main">
                <? if (!empty($item->image)): ?>
                    <img src="<?= $this->tag->thumb($item->image, 'w_300') ?>" alt="" width="100%"/>
                <? endif ?>
                <div class="paste-uploader" data-upload-url="/admin/upload/encode" data-upload-allow-num="1"
                     data-upload-allow-type="" data-upload-maxsize="" data-callback="">
                    <?= $form->render('image', array()) ?>
                    <?= $form->render('imageId', array()) ?>
                </div>
                <input name="upload" type="file" class="ace-file-input" multiple="">
            </div>
        </div>
    </div>
    <!--widgex box-->


    <div class="hr hr-double dotted"></div>
    <div class="widget-box">
        <div class="widget-header widget-header-small">
            <h5 class="lighter">Tags</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-up"></i>
                            </a>
                        </span>
        </div>

        <div class="widget-body">
            <div class="widget-main">
                <div class="form-group">
                    <input type="text" placeholder="Enter Tags ..." value="<?= $item ? $item->getTagString() : '' ?>"
                           name="tags" class="tag-input form-control">
                </div>
            </div>
        </div>
    </div>
    <!--widgex box-->

    <div class="hr hr-double dotted"></div>
    <div class="widget-box collapsed">
        <div class="widget-header widget-header-small">
            <h5 class="lighter">Publish Time</h5>
                        <span class="widget-toolbar">
                            <a data-action="collapse" href="#">
                                <i class="icon-chevron-down"></i>
                            </a>
                        </span>
        </div>

        <div class="widget-body">
            <div class="widget-main">
                <div class="input-group">
                    <input name="day" type="text" data-date-format="yyyy-mm-dd" class="form-control date-picker"
                           value="<?=
                           empty($item->createdAt) ? '' : $this->tag->datetime(
                               $item->createdAt,
                               'Y-m-d'
                           ) ?>">
                                <span class="input-group-addon">
                                    <i class="icon-calendar bigger-110"></i>
                                </span>
                </div>
                <div class="input-group bootstrap-timepicker">
                    <input name="time" type="text" class="form-control time-picker"
                           value="<?=
                           empty($item->createdAt) ? '' : $this->tag->datetime(
                               $item->createdAt,
                               'H:i:s'
                           ) ?>">
                                <span class="input-group-addon">
                                    <i class="icon-time bigger-110"></i>
                                </span>
                    <?=
                    $form->render(
                        'createdAt',
                        array()
                    )?>
                </div>
            </div>
        </div>
    </div>
    <!--widgex box-->


</div>
<!-- /.col -->

</div>
<!-- /.row -->
</div>
<!-- /.page-content -->
</form>

<script>
    $(document).ready(function () {
        var updateCreateTime = function () {
            var day = $('input[name=day]').val();
            var time = $('input[name=time]').val();
            time = time.length == 7 ? '0' + time : time;
            var timestamp = moment(day + ' ' + time).format('X');
            $('input[name=createdAt]').val(timestamp);
        }
        $('input[name=day], input[name=time]').on('change', updateCreateTime);
    });
</script>
