<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try {
            ace.settings.check('breadcrumbs', 'fixed')
        } catch (e) {
        }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="/admin/dashboard">Home</a>
        </li>

        <li>
            <a href="/admin/topic/index" class="active">Topic List</a>
        </li>
    </ul>
    <!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input"
                       autocomplete="off"/>
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div>
    <!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
                Topic List
                <a href="/admin/topic/create" class="btn btn-sm"><i class="icon-pencil align-top bigger-125"></i> Make
                    New Topic</a>
            </h3>

            <div class="table-header">
                Showing <?= $pager->offset_start ?> to <?= $pager->offset_end ?> of <?= $pager->total_items ?> Blocks
            </div>

            <div class="table-responsive dataTables_wrapper">
                <table class="table table-striped table-bordered table-hover dataTable"
                       id="blog-grid">
                    <thead>
                    <tr>
                        <th>id</th>
                        <th>name</th>
                        <th>createdAt</th>
                        <th>updatedAt</th>
                        <th>visibility</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    <? foreach ($pager->items as $item): ?>
                        <tr>

                            <td><?= $item->id ?></td>
                            <td><?= $item->name ?></td>


                            <td><?= $this->tag->datetime($item->createdAt) ?></td>
                            <td><?= $this->tag->datetime($item->updatedAt) ?></td>
                            <?$visibilities = array(
                                'invisible' => 'label-danger',
                                'visible' => 'label-success'
                            )?>
                            <td>
                                <span class="label label-sm <?=$visibilities[$item->visibility]?>"><?=$item->visibility?></span>

                            </td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs btn-success ajax-form-sumbit" data-ajax-form="1"
                                            date-method="put"
                                            data-form-action="/admin/block/visibility/<?= $item->id ?>"
                                            data-callback="window.location.reload();">
                                        <input type="hidden" data-name="visibility" value="visible">
                                        <i class="icon-ok bigger-120"></i>
                                    </button>

                                    <a class="btn btn-xs btn-info" href="/admin/block/edit/<?= $item->id ?>">
                                        <i class="icon-edit bigger-120"></i>
                                    </a>

                                    <button class="btn btn-xs ajax-form-sumbit" data-ajax-form="1"
                                            date-method="put"
                                            data-form-action="/admin/block/visibility/<?= $item->id ?>"
                                            data-callback="window.location.reload();">
                                        <input type="hidden" data-name="visibility" value="invisible">
                                        <i class="icon-eye-close bigger-120"></i>
                                    </button>


                                </div>
                            </td>
                        </tr>
                    <? endforeach ?>
                    </tbody>
                </table>

                <div class="row">

                    <div class="col-sm-12">
                        <div class="dataTables_paginate">
                            <?$this->partial(
                                "partial/paginator",
                                array(
                                    'pagerUrl' => '/admin/block/index',
                                    'pager' => $pager,
                                )
                            )?>
                        </div>
                    </div>
                </div>

            </div>
            <!--/table div-->

        </div>
        <!-- /col-->
    </div>
    <!--row end-->

</div><!-- /.page-content -->
